http:
  port: "8081"
  
sfdc:
  username: "vdileepkumar+sfdc001@gmail.com"
  password: "T@nya123"
  token: "GnOxIm8N8UIurjhY4tktR4lf"
  
file:
  accountsDir: "/Users/vdileepkumar/Documents/Learning/Mule_4/Dev_Funadementals/MUFundamentals4.1_studentFiles_22sept2018/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"
  
accounts:
  postalCode: "L4K1M7"