#%RAML 1.0 NamedExample
value:
    id: "1"
    accountNumber: "CC978213"
    accountName: "GenePoint"
    address: "345 Shoreline Park"
    city: "Mountain View"
    state: "CA"
    postal: "94043"
    country: "USA"
    phone: "(650) 867-3450"
    type: "Customer - Channel"
