#%RAML 1.0 DataType

type: object
properties: 
  id: string
  accountNumber: string
  accountName: string
  address: string
  city: string
  state: string
  postal: string
  country: string
  phone: string
  type: string